### ISSUE TITLE
Incorrect statement in 

### ISSUE THREAD

**Issue by cemeyer** [lemire/MaskedVByte#3]
Hi,

https://github.com/lemire/MaskedVByte/blob/e2dd12bc19b6a91b529368316131c582e2e8eb4a/include/varintencode.h#L19

> If the input is unsorted, then the result of the differential coding will be undefined as per the C spec

I see this was added as a result of #1; however, *unsigned* underflow it is not undefined per C.  `clang -fsanitize=integer` is just aggressively warning about possible problems in code that does not expect over/underflow, even when the standard permits it.

The result of naive differential coding is not Undefined Behavior; just an inefficient 5-byte representation when one element is slightly smaller than the previous.

Cheers,
Conrad

**Comment by lemire** [comment]
You are correct, I believe. Comment removed.

**Comment by cemeyer** [comment]
Thanks!
