### ISSUE TITLE
Dead code in multiple functions, differences between implementations

### ISSUE THREAD

**Issue by pps83** [lemire/MaskedVByte#5]
A [line before that makes this entire large block useless](https://github.com/lemire/MaskedVByte/blob/4d668512b53459145c227f0cdc76787bb28d567c/src/varintdecode.c#L2251):

```
		if (availablebytes < 16) break;

		if (availablebytes < 16) { /* dead code */
```

Then, multiple functions are almost identical copies with minor changes. For example, `masked_vbyte_decode` vs `masked_vbyte_decode_delta`. masked_vbyte_decode_delta has this `if (availablebytes < 16) break;`, while `masked_vbyte_decode` doesn't have it (similar loop with the break is inside [masked_vbyte_select_delta](https://github.com/lemire/MaskedVByte/blob/4d668512b53459145c227f0cdc76787bb28d567c/src/varintdecode.c#L2251)).

**Comment by lemire** [comment]
Pull request invited!

**Comment by pps83** [comment]
should it be deleted (the break or the block)? Should the break be added in the other function that look almost the same, but have no break?

**Comment by lemire** [comment]
Removed via commit. Closing.
